export const SPORTS_AND_POSITIONS: Record<string, string[]> = {
	Football: ["QB", "RB", "WR", "TE", "OL", "DL", "LB", "DB", "K", "P"],
	"Men's Basketball": ["PG", "SG", "SF", "PF", "C"],
	"Women's Basketball": ["PG", "SG", "SF", "PF", "C"],
	Baseball: ["P", "C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "DH"],
	Softball: ["P", "C", "1B", "2B", "3B", "SS", "LF", "CF", "RF", "DP"],
	"Men's Soccer": ["GK", "CB", "LB", "RB", "CDM", "CM", "CAM", "LW", "RW", "ST"],
	"Women's Soccer": ["GK", "CB", "LB", "RB", "CDM", "CM", "CAM", "LW", "RW", "ST"],
	Volleyball: ["S", "L", "OH", "MB", "RS", "OP"],
	"Men's Lacrosse": ["A", "M", "D", "GK", "LSM", "SSDM", "FO"],
	"Women's Lacrosse": ["A", "M", "D", "GK"],
	Wrestling: ["125", "133", "141", "149", "157", "165", "174", "184", "197", "285"],
	"Track & Field": [
		"Sprints",
		"Distance",
		"Hurdles",
		"Jumps",
		"Throws",
		"Pole Vault",
		"Multi-Event",
	],
	Swimming: ["Freestyle", "Backstroke", "Breaststroke", "Butterfly", "IM", "Diving"],
	Golf: ["Player"],
	Tennis: ["Singles", "Doubles"],
	"Ice Hockey": ["C", "LW", "RW", "D", "G"],
	Gymnastics: ["All-Around", "Bars", "Beam", "Floor", "Vault"],
	Other: ["Athlete"],
};

export const SPORTS = Object.keys(SPORTS_AND_POSITIONS);

export const US_STATES = [
	{ code: "AL", name: "Alabama" },
	{ code: "AK", name: "Alaska" },
	{ code: "AZ", name: "Arizona" },
	{ code: "AR", name: "Arkansas" },
	{ code: "CA", name: "California" },
	{ code: "CO", name: "Colorado" },
	{ code: "CT", name: "Connecticut" },
	{ code: "DE", name: "Delaware" },
	{ code: "DC", name: "District of Columbia" },
	{ code: "FL", name: "Florida" },
	{ code: "GA", name: "Georgia" },
	{ code: "HI", name: "Hawaii" },
	{ code: "ID", name: "Idaho" },
	{ code: "IL", name: "Illinois" },
	{ code: "IN", name: "Indiana" },
	{ code: "IA", name: "Iowa" },
	{ code: "KS", name: "Kansas" },
	{ code: "KY", name: "Kentucky" },
	{ code: "LA", name: "Louisiana" },
	{ code: "ME", name: "Maine" },
	{ code: "MD", name: "Maryland" },
	{ code: "MA", name: "Massachusetts" },
	{ code: "MI", name: "Michigan" },
	{ code: "MN", name: "Minnesota" },
	{ code: "MS", name: "Mississippi" },
	{ code: "MO", name: "Missouri" },
	{ code: "MT", name: "Montana" },
	{ code: "NE", name: "Nebraska" },
	{ code: "NV", name: "Nevada" },
	{ code: "NH", name: "New Hampshire" },
	{ code: "NJ", name: "New Jersey" },
	{ code: "NM", name: "New Mexico" },
	{ code: "NY", name: "New York" },
	{ code: "NC", name: "North Carolina" },
	{ code: "ND", name: "North Dakota" },
	{ code: "OH", name: "Ohio" },
	{ code: "OK", name: "Oklahoma" },
	{ code: "OR", name: "Oregon" },
	{ code: "PA", name: "Pennsylvania" },
	{ code: "RI", name: "Rhode Island" },
	{ code: "SC", name: "South Carolina" },
	{ code: "SD", name: "South Dakota" },
	{ code: "TN", name: "Tennessee" },
	{ code: "TX", name: "Texas" },
	{ code: "UT", name: "Utah" },
	{ code: "VT", name: "Vermont" },
	{ code: "VA", name: "Virginia" },
	{ code: "WA", name: "Washington" },
	{ code: "WV", name: "West Virginia" },
	{ code: "WI", name: "Wisconsin" },
	{ code: "WY", name: "Wyoming" },
];

export const ELIGIBILITY_STATUSES = [
	"Freshman",
	"Sophomore",
	"Junior",
	"Senior",
	"Graduate",
	"Redshirt Freshman",
	"Redshirt Sophomore",
	"Redshirt Junior",
	"Redshirt Senior",
	"HS Freshman",
	"HS Sophomore",
	"HS Junior",
	"HS Senior",
] as const;

export type EligibilityStatus = (typeof ELIGIBILITY_STATUSES)[number];

export const GRAD_YEARS = [2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032];

// NIL is allowed in High School for these states (as of 2026)
export const HS_NIL_STATES = new Set([
	"CA",
	"FL",
	"NY",
	"NJ",
	"IL",
	"NC",
	"TX",
	"GA",
	"CO",
	"AZ",
	"CT",
	"DC",
	"KS",
	"KY",
	"LA",
	"MD",
	"MA",
	"MN",
	"MO",
	"MT",
	"NE",
	"NV",
	"NH",
	"NM",
	"ND",
	"OK",
	"OR",
	"RI",
	"SC",
	"SD",
	"TN",
	"UT",
	"VT",
	"VA",
	"WA",
	"WV",
	"WI",
	"WY",
	"PA",
	"AR",
	"ID",
	"IA",
	"ME",
	"MS",
	"AK",
]);

/** Compute NIL eligibility at the point of onboarding (best-effort, not legal advice) */
export function computeNilEligible(division: string, state: string): boolean {
	if (division === "High School") return HS_NIL_STATES.has(state);
	return true; // All college divisions (D1, D2, D3, NAIA, NJCAA) allow NIL
}
